---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: boshcpi/cpi-certification

inputs:
  - name: bosh-cli
  - name: bats
  - name: bats-config
  - name: stemcell

run:
  path: bats/ci/tasks/run-bats.sh
